export const EDIT_PENDING_STATUS = 'EDIT_PENDING_STATUS'
export const EDIT_UPLOADING_STATUS = 'EDIT_UPLOADING_STATUS'
export const EDIT_UPLOADED_STATUS = 'EDIT_UPLOADED_STATUS'
export const EDIT_SUCCEEDED_STATUS = 'EDIT_SUCCEEDED_STATUS'
